name: Build and deploy app

on:
  push:
    branches: [main]

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: echo "${{secrets.ENV_VARS}}" > .env

      - name: Test the app
        run: npm test

  validate-deployment:
    needs: test-app
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Remove development files and folder
        run: rm -rf src/ node_modules/

      - name: Install production packages
        run: npm i --omit=dev

      - name: Start application
        run: npm start &

  deploy:
    needs: [test-app, validate-deployment]

    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Move files to AWS EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist,package*"
          target: "brewtopia"
