name: Build and deploy app

on:
  push:
    branches: [main]

env:
  HUSKY: 0
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: echo "${{secrets.ENV_VARS}}" > .env

      - name: Test the app
        run: npm test

  validate-deployment:
    needs: test-app
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Remove development files and folder
        run: rm -rf src/ node_modules/

      - name: Install production packages
        run: npm i --omit=dev

      - name: Start application
        run: npm start &

  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel Project
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  # deploy:
  #   needs: [test-app, validate-deployment]

  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: "20.x"

  #     - name: Checkout the repository
  #       uses: actions/checkout@v4

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Build the app
  #       run: npm run build

  #     - name: Move files to server
  #       uses: appleboy/scp-action@master
  #       with:
  #         host: ${{ secrets.REMOTE_HOST }}
  #         username: ${{ secrets.REMOTE_USER }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         source: "dist,package*"
  #         target: "brewtopia"
