name: Build and deploy app

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Move files to AWS EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist,package*"
          target: "brewtopia"
