name: Build and deploy app

on:
  push:
    branches: [main]

env:
  HUSKY: 0
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  test-application:
    name: Test Application
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: echo "${{secrets.ENV_VARS}}" > .env

      - name: Test the app
        run: npm test

  validate-deployment:
    name: Validate Deployment
    needs: test-application
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Remove development files and folder
        run: rm -rf src/ node_modules/

      - name: Install production packages
        run: npm i --omit=dev

      - name: Start application
        run: npm start &

  deploy-to-vercel:
    name: Deploy to Vercel
    needs: validate-deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy Project Artifacts to Vercel Project
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
